System.register([], function (exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    return {
        setters: [],
        execute: function () {
            exports_1("default", [
                [
                    //logic layer
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
                    [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]
                ], [
                    //meta layer
                    [{ w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }],
                    [{ w: "w" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { w: "w" }],
                    [{ w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }],
                    [{ w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }],
                    [{ w: "w" }, { f: "l" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "l" }, { w: "w" }],
                    [{ w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }],
                    [{ b: "b" }, { b: "b" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { b: "b" }, { b: "b" }],
                    [{ w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }],
                    [{ b: "p" }, { b: "p" }, { b: "p" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { b: "p" }, { b: "p" }, { b: "p" }],
                    [{ w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { b: "p" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { b: "p" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }],
                    [{ b: "b" }, { b: "b" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { b: "p" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { b: "p" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { b: "b" }, { b: "b" }],
                    [{ b: "b" }, { b: "b" }, { w: "w" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { b: "p" }, { b: "p" }, { b: "p" }, { b: "p" }, { b: "p" }, { b: "p" }, { b: "p" }, { b: "p" }, { b: "p" }, { b: "p" }, { b: "p" }, { b: "p" }, { b: "p" }, { b: "p" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { w: "w" }, { b: "b" }, { b: "b" }],
                    [{ b: "b" }, { b: "b" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { b: "p" }, { w: "w" }, { w: "w" }, { w: "w" }, { d: "d" }, { d: "d" }, { w: "w" }, { w: "w" }, { w: "w" }, { b: "p" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { b: "b" }, { b: "b" }],
                    [{ b: "b" }, { b: "b" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { b: "p" }, { w: "w" }, { b: "b" }, { b: "b" }, { b: "s" }, { b: "s" }, { b: "b" }, { b: "b" }, { w: "w" }, { b: "p" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { b: "b" }, { b: "b" }],
                    [{ b: "b" }, { b: "b" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { b: "p" }, { b: "p" }, { b: "p" }, { w: "w" }, { c: "b" }, { c: "b" }, { c: "b" }, { c: "b" }, { c: "b" }, { c: "b" }, { w: "w" }, { b: "p" }, { b: "p" }, { b: "p" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { b: "b" }, { b: "b" }],
                    [{ b: "b" }, { b: "b" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { b: "p" }, { w: "w" }, { b: "b" }, { b: "b" }, { b: "b" }, { b: "b" }, { b: "b" }, { b: "b" }, { w: "w" }, { b: "p" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { b: "b" }, { b: "b" }],
                    [{ w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { b: "p" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { b: "p" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }],
                    [{ b: "p" }, { b: "p" }, { b: "p" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { w: "w" }, { w: "w" }, { b: "p" }, { b: "p" }, { b: "p" }, { b: "p" }, { b: "p" }, { b: "p" }, { b: "p" }, { b: "p" }, { b: "p" }, { b: "p" }, { w: "w" }, { w: "w" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { b: "p" }, { b: "p" }, { b: "p" }],
                    [{ w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { b: "p" }, { w: "w" }, { w: "w" }, { b: "p" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }],
                    [{ b: "b" }, { b: "b" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { b: "p" }, { w: "w" }, { w: "w" }, { b: "p" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { b: "b" }, { b: "b" }],
                    [{ b: "b" }, { b: "b" }, { w: "w" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { w: "w" }, { b: "b" }, { b: "b" }],
                    [{ b: "b" }, { b: "b" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { b: "b" }, { b: "b" }],
                    [{ w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }],
                    [{ w: "w" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { w: "w" }],
                    [{ w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }],
                    [{ w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }],
                    [{ w: "w" }, { f: "l" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "l" }, { w: "w" }],
                    [{ w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }],
                    [{ w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { f: "s" }, { w: "w" }],
                    [{ w: "w" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { f: "s" }, { w: "w" }],
                    [{ w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }, { w: "w" }]
                ]
            ]);
        }
    };
});
//# sourceMappingURL=layout.js.map